version: '3'

services:
  bot:
    container_name: bot
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    depends_on:
      - mongo
    networks:
      - bridge
  mongo:
    image: mongo:latest
    container_name: mongo
    restart: on-failure
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_INITDB_ROOT_USERNAME}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_INITDB_ROOT_PASSWORD}
    volumes:
      - mongodb:/data/db
    ports:
      - "27017:27017"
    networks:
      - bridge
  mongo-express:
    image: mongo-express
    restart: on-failure
    ports:
      - "8081:8081"
    networks:
      - bridge
    env_file:
      - .env
    environment:
    - ME_CONFIG_MONGODB_ADMINUSERNAME=${MONGO_INITDB_ROOT_USERNAME}
    - ME_CONFIG_MONGODB_ADMINPASSWORD=${MONGO_INITDB_ROOT_PASSWORD}
    - ME_CONFIG_MONGODB_URL=${MONGOURI}
    - ME_CONFIG_BASICAUTH=false
    depends_on:
      - mongo

volumes:
  mongodb:

networks:
  bridge:
