global:
  scrape_interval: 15s
  scrape_timeout: 10s
  evaluation_interval: 15s
alerting:
  alertmanagers:
    - static_configs:
        - targets: []
      scheme: http
      timeout: 10s
      api_version: v1
scrape_configs:
  - job_name: dev-push-gateway
    metrics_path: /metrics
    scheme: http
    honor_labels: true
    static_configs:
      - targets: ['pushgateway:9091']
        labels:
          service: 'pushgateway'
