{
 "title": "Discord stats",
 "time": { "from": "2024-08-12T18:30:43.429Z", "to": "2024-08-12T19:00:43.429Z" },
 "panels": [
  {
   "title": "Guilds count",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 5, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "guilds{job=\"stats\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Commands Interaction chart",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 19, "x": 5, "y": 0 },
   "targets": [
    {
     "expr": "command_interactions{job=\"stats\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Users count",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 5, "x": 0, "y": 6 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "users{job=\"stats\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Buttons Interaction chart",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 19, "x": 5, "y": 9 },
   "targets": [
    {
     "expr": "button_interactions{job=\"stats\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Forms count",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 5, "x": 0, "y": 12 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "forms{job=\"stats\"}",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}